config/routes.rb
Rails.application.routes.draw do

  root to: "main#index"

  post 'change_background', to: 'main#change_background'

  get "galerija", to: "galerija#galerijaIndex"

  get "registracija", to: "registracija#new"
  post "registracija", to: "registracija#create"

  get "prijava", to: "session#new"
  post "prijava", to: "session#create"

  delete "odjava", to: "session#destroy"

  get "nalozi", to: "galerija#new"
  post "nalozi", to: "galerija#create"

  get "posta", to: "mail#new"
  post "posta", to: "mail#send"

  resources :notepads



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/notepad.rb
class Notepad < ApplicationRecord
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
#email:string
#password_digest:string

#password:string virtual
#password_confirmation:string virtual
class User < ApplicationRecord
    has_many :pictures
    has_many :notepads
    has_secure_password

    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    before_action :set_background_color
    def set_background_color
        session[:background_color] ||= "white"
        @background_color = session[:background_color]
    end
end

app/controllers/galerija_controller.rb
class GalerijaController < ApplicationController
    def galerijaIndex
        @slike = Picture.all
    end

    def new
        if Current.user
            @slika = Picture.new
        else
            redirect_to prijava_path, notice: "Potrebna je prijava."
        end
    end

    def create
        @slika = Current.user.pictures.new(picture_params)
        if @slika.save
            redirect_to root_path, notice: "Slika je bila uspešno naložena."
        else
            render :new, alert: "Napaka pri nalaganju slike."
        end
      end

    private

  def picture_params
    params.require(:picture).permit(:name, :image)
  end
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
  def new
    @email = params[:email]
  end

  def send_mail
    email = params[:email]
    tema = params[:tema]
    vsebina = params[:vsebina]

    UserMailer.sample_email(email: email, tema: tema, vsebina: vsebina).deliver

    redirect_to root_path, notice: "E-pošta uspešno poslana!"
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end

    def change_background
        session[:background_color] = params[:color]
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/notepads_controller.rb
class NotepadsController < ApplicationController

  def index
    if Current.user
      @notepads = Current.user.notepads
      @notepad = Notepad.new
    else
      redirect_to prijava_path, notice: "Potrebna je prijava."
    end
  end

  def create
    @notepad = Current.user.notepads.build(notepad_params)
    if @notepad.save
      redirect_to notepads_path, notice: "Beležka ustvarjena."
    else
      @notepads = current_user.notepads
      render :index
    end
  end

  def update
    @notepad = Current.user.notepads.find(params[:id])
    if @notepad.update(notepad_params)
      redirect_to notepads_path, notice: "Beležka posodobljena."
    else
      render :index
    end
  end

  def destroy
    @notepad = Current.user.notepads.find(params[:id])
    @notepad.destroy
    redirect_to notepads_path, notice: "Beležka izbrisana."
  end


  private

  def notepad_params
    params.require(:notepad).permit(:name, :text)
  end


end

app/controllers/registracija_controller.rb
class RegistracijaController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Uspešno registrirani"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Uspešna prijava"
        else
            flash[:alert] = "Nepravilen email ali geslo"
            render :new
        end
    end
    
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Odjavleni"
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galerija/galerijaIndex.html.erb
<h1>To je galerija naloženih slik</h1>
<br>
<div class="gallery">
  <% @slike.each_slice(5) do |slike_v_vrstici| %>
    <div class="row">
      <% slike_v_vrstici.each do |slika| %>
        <div class="col">
          <%= image_tag slika.image, class: "image" %>
          <p>Naziv: <%= slika.name %></p> 
          <p>Naložil: <%= link_to slika.user.email, posta_path(email: slika.user.email), class: "btn btn-primary" %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/galerija/new.html.erb
<h1> Objavi novo sliko </h1>

<div class="form">
  <%= form_with model: @slika, url: nalozi_path do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.submit "Objavi", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails spletna stran</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: <%= @background_color %>;">
  <%= render partial: "shared/navbar" %>
   <div class:"container-sm">
     <%= yield %>
   </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>To je domača stran</h1>

<%= form_tag(change_background_path, method: :post) do %>
  <%= select_tag :color, options_for_select(["White", "LightGray", "SkyBlue", "LightGreen", "LightPink"])
 %>
  <%= submit_tag "Change Background" %>
<% end %>

app/views/notepads/index.html.erb
<h1>Moje beležke</h1>

<%= form_with(model: @notepad, url: notepads_path, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "Dodaj beležko", class: "btn btn-primary" %>
  </div>
<% end %>

<% @notepads.each do |notepad| %>
  <div class="container">
    <%= form_with(model: notepad, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :text %>
        <%= form.text_area :text, class: "form-control" %>
      </div>
      <div class="form-group d-flex justify-content-between">
        <%= form.submit "Shrani", class: "btn btn-primary" %>
        <% if notepad.persisted? %>
          <%= link_to "Izbriši", notepad_path(notepad), method: :delete, class: "btn btn-danger", data: { turbo_method: "delete", turbo_confirm: "Si prepričan?" } %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/registracija/new.html.erb
<h1>Registriraj se</h1>

<div class="form">
    <%=form_with model: @user, url: registracija_path do |form|%>
    
        <div class ="mb-3">
            <%= form.label :email %>
            <%= form.text_field (:email), class: "form-control" %>
        </div>
        <div class ="mb-3">
            <%= form.label :password %>
            <%= form.password_field (:password), class: "form-control"%>
        </div>
        <div class ="mb-3">
            <%= form.label :password_confirmation %>
            <%= form.password_field (:password_confirmation), class: "form-control"%>
        </div>
    
        <div class="mb-3">
            <%= form.submit "Registriraj se"%>
        </div>
    <%end%>
</div>

app/views/session/new.html.erb
<h1> Prijavi se </h1>

<div class="form">
    <%= form_with url: prijava_path do |form| %>
        <div class ="mb-3">
            <%= form.label :email %>
            <%= form.text_field (:email), class: "form-control" %>
        </div>
        <div class ="mb-3">
            <%= form.label :password %>
            <%= form.password_field (:password), class: "form-control"%>
        </div>
    
        <div class="mb-3">
            <%= form.submit "Prijavi se"%>
        </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid d-flex justify-content-between"> 
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/">Domov</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/galerija">Galerija</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/nalozi">Naloži</a>
        </li>
        <li class="nav-item">
          <%= link_to "Beležka", notepads_path, class: "nav-link" %>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto"> 
        <% if Current.user %>
          <li class="d-flex align-items-center" >
            <%= Current.user.email %>
          </li>
          <li class="nav-item">
            <%= button_to "Odjava", odjava_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Registracija", registracija_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Prijava", prijava_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>